CREATE SCHEMA IF NOT EXISTS records;
CREATE SCHEMA IF NOT EXISTS pharmacy;
CREATE SCHEMA IF NOT EXISTS clinical;
CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS notify;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
